# Generated by Django 5.0.6 on 2024-06-27 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado_actual', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], max_length=10)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('repuestos_utilizados', models.TextField()),
                ('tecnico', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.solicitud')),
            ],
        ),
    ]
